package com.guidewire.pc;

import com.guidewire.pc.batch.BatchProcessManager;
import com.guidewire.pc.batch.BatchProcessResult;
import com.guidewire.pc.constants.PCConstants;
import com.guidewire.pc.model.PolicyPeriod;
import com.guidewire.pc.service.DataStoreService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("Guidewire OOTB Pre-Renewal Batch Engine Tests")
public class PreRenewalBatchProcessTest {

    @Test
    @DisplayName("Should run PreRenewal batch process and generate renewal branches using Virtual Threads")
    public void testPreRenewalBatchProcessExecution() {
        DataStoreService dataStore = DataStoreService.getInstance();

        // Create sample active issued policy
        PolicyPeriod period = new PolicyPeriod();
        period.setJobNumber("S000_PRERENEW_TEST");
        period.setPolicyNumber("POL-PRERENEW-9001");
        period.setStatus(PCConstants.STATUS_ISSUED);
        period.setProductCode(PCConstants.PRODUCT_COMMERCIAL_AUTO);
        period.setEffectiveDate("2026-01-01");
        period.setExpirationDate("2026-09-01");
        period.setBodilyInjuryLimit("$500k/$500k");
        period.setPropertyDamageLimit("$250k");
        dataStore.createSubmission(period);

        BatchProcessResult result = BatchProcessManager.getInstance().runProcess("PreRenewal");

        assertNotNull(result);
        assertTrue(result.isSuccess());

        // Verify renewal job exists in dataStore
        boolean renewalFound = dataStore.getSubmissions().stream().anyMatch(sub ->
                PCConstants.JOB_TYPE_RENEWAL.equalsIgnoreCase(sub.getJobType()) &&
                "POL-PRERENEW-9001".equalsIgnoreCase(sub.getPolicyNumber())
        );
        assertTrue(renewalFound, "Renewal job should be generated by PreRenewal batch process");
    }
}
